<?php
require 'db.php';
$s=$pdo->prepare("SELECT c.cart_id FROM carts c WHERE c.session_token=?");$s->execute([$cartToken]);$cart=$s->fetch();
$items=[];$subtotal=0;
if($cart){$s=$pdo->prepare("SELECT ci.cart_item_id,ci.quantity,p.product_id,p.name,p.price,p.image,p.stock FROM cart_items ci JOIN products p ON p.product_id=ci.product_id WHERE ci.cart_id=? ORDER BY ci.cart_item_id DESC");$s->execute([$cart['cart_id']]);$items=$s->fetchAll();foreach($items as $i)$subtotal += $i['price']*$i['quantity'];}
$delivery=$items?250:0;$total=$subtotal+$delivery;
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Your Cart | Ceylon Spice Hub</title><link rel="stylesheet" href="style.css"></head>
<body><header class="header"><div class="container nav-wrap"><a class="brand" href="index.php"><span>Ceylon</span><small>SPICE HUB</small></a><a class="btn btn-primary" href="index.php#shop">← Continue Shopping</a></div></header>
<main class="cart-page"><div class="container"><p class="eyebrow">YOUR ORDER</p><h1 class="page-title">Shopping Cart</h1>
<?php if(!$items): ?><div class="cart-empty"><div>🛒</div><h2>Your cart is empty</h2><p>Add some authentic Ceylon spices to get started.</p><a class="btn btn-primary" href="index.php#shop">EXPLORE SPICES</a></div>
<?php else: ?><div class="cart-layout"><div class="cart-items"><?php foreach($items as $i): ?><div class="cart-row"><img src="<?=e($i['image'])?>" alt="<?=e($i['name'])?>"><div class="cart-details"><small><?=e($i['weight']??'')?></small><h3><?=e($i['name'])?></h3><strong><?=money((float)$i['price'])?></strong><div class="qty"><button onclick="updateQty(<?=$i['cart_item_id']?>,<?=$i['quantity']-1?>)">−</button><span><?=$i['quantity']?></span><button onclick="updateQty(<?=$i['cart_item_id']?>,<?=$i['quantity']+1?>)">+</button></div></div><b><?=money((float)$i['price']*$i['quantity'])?></b><button class="remove" onclick="removeItem(<?=$i['cart_item_id']?>)">Remove</button></div><?php endforeach; ?></div>
<div class="summary"><h2>Order Summary</h2><div><span>Subtotal</span><b><?=money((float)$subtotal)?></b></div><div><span>Delivery</span><b><?=money((float)$delivery)?></b></div><hr><div class="grand"><span>Total</span><b><?=money((float)$total)?></b></div><a class="btn btn-primary checkout-btn" href="checkout.php">PROCEED TO CHECKOUT →</a><small>Secure checkout · Islandwide delivery</small></div></div><?php endif; ?></div></main>
<style>
.cart-page{padding:65px 0}.page-title{font:700 42px "Playfair Display";margin-bottom:30px}.cart-layout{display:grid;grid-template-columns:1fr 330px;gap:35px}.cart-items{border-top:1px solid #e7e3da}.cart-row{display:grid;grid-template-columns:90px 1fr auto auto;gap:18px;align-items:center;padding:20px 0;border-bottom:1px solid #e7e3da}.cart-row img{width:90px;height:90px;object-fit:cover}.cart-details small{color:#b27b2e;font-size:9px}.cart-details h3{font:700 16px "Playfair Display";margin:3px 0}.cart-details strong{font-size:12px}.qty{display:flex;align-items:center;gap:12px;margin-top:9px}.qty button{width:27px;height:27px;border:1px solid #ddd;background:#fff;cursor:pointer}.qty span{font-size:11px}.remove{border:0;background:none;color:#a04444;font-size:10px;cursor:pointer}.summary{background:#fbf8f1;padding:25px;height:max-content}.summary h2{font:700 23px "Playfair Display";margin-bottom:20px}.summary>div{display:flex;justify-content:space-between;font-size:11px;margin:13px 0}.summary hr{border:0;border-top:1px solid #ddd}.summary .grand{font-size:14px}.checkout-btn{width:100%;margin-top:12px}.summary>small{display:block;text-align:center;color:#777;font-size:9px;margin-top:10px}.cart-empty{text-align:center;padding:80px 20px;border:1px solid #e7e3da;background:#fbf8f1}.cart-empty div{font-size:45px}.cart-empty h2{font:700 28px "Playfair Display";margin:10px}.cart-empty p{font-size:12px;color:#777;margin-bottom:20px}
@media(max-width:750px){.cart-layout{grid-template-columns:1fr}.cart-row{grid-template-columns:70px 1fr auto}.cart-row> b{grid-column:2}.cart-row .remove{grid-column:3;grid-row:2}.cart-row img{width:70px;height:70px}}
</style><script>
function updateQty(id,qty){if(qty<1){removeItem(id);return}fetch('update_cart.php',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:'id='+id+'&quantity='+qty}).then(()=>location.reload())}
function removeItem(id){fetch('update_cart.php',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:'id='+id+'&quantity=0'}).then(()=>location.reload())}
</script></body></html>