<?php
require 'db.php';
$s=$pdo->prepare("SELECT c.cart_id FROM carts c WHERE c.session_token=?");$s->execute([$cartToken]);$cart=$s->fetch();$items=[];$subtotal=0;
if($cart){$s=$pdo->prepare("SELECT ci.cart_item_id,ci.product_id,ci.quantity,p.name,p.price,p.image,p.stock FROM cart_items ci JOIN products p ON p.product_id=ci.product_id WHERE ci.cart_id=?");$s->execute([$cart['cart_id']]);$items=$s->fetchAll();foreach($items as $i)$subtotal += $i['price']*$i['quantity'];}
if(!$items){header('Location: cart.php');exit;}$delivery=250;$total=$subtotal+$delivery;
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Checkout | Ceylon Spice Hub</title><link rel="stylesheet" href="style.css"></head><body>
<header class="header"><div class="container nav-wrap"><a class="brand" href="index.php"><span>Ceylon</span><small>SPICE HUB</small></a><span style="margin-left:auto;font-size:11px;color:#777">Secure Checkout 🔒</span></div></header>
<main class="checkout-page"><div class="container"><p class="eyebrow">CHECKOUT</p><h1 class="page-title">Complete your order</h1><div class="checkout-layout">
<form class="checkout-form" action="place_order.php" method="post"><h2>Delivery Details</h2><div class="form-grid"><label>Full Name<input name="customer_name" required placeholder="Your full name"></label><label>Email<input type="email" name="email" required placeholder="you@example.com"></label><label>Phone Number<input name="contact" required placeholder="+94 7X XXX XXXX"></label><label>City<input name="city" required placeholder="Colombo"></label></div><label>Delivery Address<textarea name="address" required rows="4" placeholder="House number, street, area"></textarea></label><h2>Payment Method</h2><label class="payment-option"><input type="radio" name="payment_method" value="Cash on Delivery" checked> <span>💵 Cash on Delivery <small>Pay when your order arrives.</small></span></label><label class="payment-option"><input type="radio" name="payment_method" value="Bank Transfer"> <span>🏦 Bank Transfer <small>Payment details can be provided after ordering.</small></span></label><button class="btn btn-primary submit-order">PLACE ORDER • <?=money((float)$total)?></button></form>
<aside class="checkout-summary"><h2>Your Order</h2><?php foreach($items as $i): ?><div class="order-mini"><img src="<?=e($i['image'])?>" alt=""><div><b><?=e($i['name'])?></b><small><?=$i['quantity']?> × <?=money((float)$i['price'])?></small></div></div><?php endforeach; ?><hr><div><span>Subtotal</span><b><?=money((float)$subtotal)?></b></div><div><span>Delivery</span><b><?=money((float)$delivery)?></b></div><div class="total"><span>Total</span><b><?=money((float)$total)?></b></div></aside>
</div></div></main>
<style>.checkout-page{padding:60px 0}.page-title{font:700 42px "Playfair Display";margin-bottom:30px}.checkout-layout{display:grid;grid-template-columns:1fr 350px;gap:35px}.checkout-form,.checkout-summary{border:1px solid #e7e3da;padding:28px}.checkout-form h2,.checkout-summary h2{font:700 23px "Playfair Display";margin-bottom:20px}.checkout-form label{display:block;font-size:10px;font-weight:600;margin:15px 0}.form-grid{display:grid;grid-template-columns:1fr 1fr;gap:0 15px}.checkout-form input,.checkout-form textarea{display:block;width:100%;border:1px solid #ddd;padding:11px;margin-top:6px;outline:0;font-size:11px}.checkout-form input:focus,.checkout-form textarea:focus{border-color:#0d5135}.payment-option{border:1px solid #e7e3da;padding:13px;display:flex!important;gap:10px;align-items:flex-start}.payment-option input{width:auto!important;margin:2px 0!important}.payment-option span{font-size:11px}.payment-option small{display:block;color:#777;margin-top:3px}.submit-order{width:100%;margin-top:10px}.checkout-summary{background:#fbf8f1;height:max-content}.order-mini{display:flex;gap:12px;margin:14px 0}.order-mini img{width:55px;height:55px;object-fit:cover}.order-mini b,.order-mini small{display:block;font-size:10px}.order-mini small{color:#777;margin-top:3px}.checkout-summary>div:not(.order-mini){display:flex;justify-content:space-between;font-size:10px;margin:13px 0}.checkout-summary hr{border:0;border-top:1px solid #ddd}.checkout-summary .total{font-size:14px}@media(max-width:750px){.checkout-layout,.form-grid{grid-template-columns:1fr}.checkout-page{padding:35px 0}}
</style></body></html>